#include "audio/acquisition.h"
#include "check.h"

#include <cmath>
#include <limits>
#include <numbers>
#include <vector>

using namespace umbriel::audio;

namespace {
  std::vector<float> tone(double frequency, float amplitude = 1) {
    std::vector<float> samples(kWindowFrames);
    for (size_t n = 0; n < samples.size(); ++n) {
      samples[n] = amplitude * std::sin(2 * std::numbers::pi * frequency * n / kSampleRate);
    }
    return samples;
  }

  void golden(const std::vector<float>& samples, const std::array<int, 19>& expected, size_t channels = 1) {
    Linear16 analyzer;
    const auto features = analyzer.analyze(samples, channels, static_cast<double>(kWindowFrames) / kSampleRate);
    CHECK(features.has_value());
    if (!features) {
      return;
    }
    CHECK_EQ(std::lround(features->rms * 65535), expected[0]);
    CHECK_EQ(std::lround(features->peak * 65535), expected[1]);
    CHECK_EQ(std::lround(features->envelope * 65535), expected[2]);
    for (size_t band = 0; band < 16; ++band) {
      CHECK_EQ(std::lround(features->bands[band] * 65535), expected[band + 3]);
    }
  }
} // namespace

UMBRIEL_TEST(independentDirectDftGoldenVectors) {
  // Generated by tests/audio/golden.py, which shares no FFT implementation.
  golden(std::vector<float>(kWindowFrames), {});
  golden(
      std::vector<float>(kWindowFrames, 1), {65535, 65535, 64616, 30427, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
  );
  golden(tone(1500), {46340, 65535, 45690, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46340, 0, 0, 0, 0, 0, 0});
  std::vector<float> impulse(kWindowFrames);
  impulse[kWindowFrames / 2] = 1;
  golden(impulse, {1448, 65535, 1428, 68, 97, 97, 118, 145, 174, 216, 264, 324, 389, 483, 591, 724, 870, 1079, 1079});
  auto twoTones = tone(750, 0.5F);
  const auto high = tone(6000, 0.25F);
  for (size_t i = 0; i < twoTones.size(); ++i) {
    twoTones[i] += high[i];
  }
  golden(twoTones, {25905, 48522, 25542, 0, 0, 0, 0, 0, 0, 0, 23170, 0, 0, 0, 0, 11585, 0, 0, 0});
  golden(tone(900), {46382, 65535, 45731, 0, 1, 1, 1, 1, 2, 9, 33462, 32058, 3, 0, 0, 0, 0, 0, 0});
}

UMBRIEL_TEST(antiPhaseChannelPowerDoesNotCancel) {
  const auto mono = tone(1500);
  std::vector<float> stereo;
  for (float sample : mono) {
    stereo.push_back(sample);
    stereo.push_back(-sample);
  }
  golden(stereo, {46340, 65535, 45690, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46340, 0, 0, 0, 0, 0, 0}, 2);
}

UMBRIEL_TEST(envelopeStepsResetAndPrecision) {
  Linear16 analyzer;
  std::vector<float> full(kWindowFrames, 1);
  std::vector<float> silent(kWindowFrames);
  auto result = analyzer.analyze(full, 1, 0.010);
  CHECK(result.has_value());
  CHECK_EQ(result->envelope, quantize(1 - std::exp(-1)));
  result = analyzer.analyze(silent, 1, 0.150);
  CHECK_EQ(result->envelope, quantize((1 - std::exp(-1)) * std::exp(-1)));
  result = analyzer.analyze(silent, 1, 5);
  CHECK_EQ(result->envelope, 0);
  analyzer.reset();
  result = analyzer.analyze(full, 1, 0);
  CHECK_EQ(result->envelope, 0);
  CHECK_EQ(quantize(1.0 / 65535), 1.0F / 65535);
}

UMBRIEL_TEST(invalidDataRejectsWithoutUpdatingEnvelope) {
  Linear16 analyzer;
  std::vector<float> input(kWindowFrames, 2);
  auto result = analyzer.analyze(input, 1, 0.01);
  CHECK_EQ(result->rms, 1);
  input[0] = std::numeric_limits<float>::infinity();
  CHECK(!analyzer.analyze(input, 1, 0.01));
  input[0] = std::numeric_limits<float>::quiet_NaN();
  CHECK(!analyzer.analyze(input, 1, 0.01));
  CHECK(!analyzer.analyze({}, 0, 0.01));
  CHECK(!analyzer.analyze({}, 9, 0.01));
  CHECK(!analyzer.analyze({}, 1, -1));
}

UMBRIEL_TEST(ringOverflowDropsOldAudioAndAdvancesGeneration) {
  AnalysisStream stream;
  std::vector<float> full(kRingFrames, 1);
  CHECK(stream.ingest(full, 100));
  const auto first = stream.next(7);
  CHECK(first.has_value());
  CHECK_EQ(first->generation, 1U);
  CHECK_EQ(first->observationNs, 100U);
  CHECK(stream.ingest(std::vector<float>(kRingFrames * 2), 200));
  CHECK_EQ(stream.queuedFrames(), kRingFrames);
  CHECK_EQ(stream.generation(), 2U);
  const auto second = stream.next(7);
  CHECK_EQ(second->generation, 2U);
  CHECK_EQ(second->sequence, 1U);
  CHECK_EQ(second->observationNs, 200U);
  CHECK_EQ(second->features, Features{});
  CHECK(!stream.ingest(full, 199));
  CHECK_EQ(stream.generation(), 2U);
}

UMBRIEL_TEST(acquisitionLossFadesSameGenerationAndRejectsQueuedOldBuffers) {
  Acquisition acquisition;
  const auto samples = tone(1500, .5F);
  CHECK(acquisition.ingest(1, samples, 100, 110, 7));
  const auto first = acquisition.take();
  CHECK(first.has_value());
  CHECK(acquisition.available());
  CHECK(acquisition.publishedGeneration() < first->generation);
  acquisition.published(first->generation);
  const auto generation = acquisition.generation();
  CHECK(acquisition.ingest(1, samples, 120, 130, 7));
  CHECK(acquisition.pending());
  acquisition.invalidate(150);
  CHECK(!acquisition.available());
  CHECK(!acquisition.pending());
  CHECK_EQ(acquisition.generation(), generation);
  CHECK(!acquisition.ingest(1, samples, 140, 200, 7));
  CHECK_EQ(acquisition.generation(), generation);
  // Idle status and an incomplete replacement window retain the loss generation.
  CHECK(acquisition.ingest(1, std::span(samples).first(100), 160, 210, 7));
  CHECK_EQ(acquisition.generation(), generation);
  CHECK(!acquisition.available());
  CHECK(acquisition.ingest(1, std::span(samples).subspan(100), 170, 220, 7));
  const auto replacement = acquisition.take();
  CHECK(replacement.has_value());
  CHECK_EQ(replacement->generation, generation + 1);
  CHECK_EQ(replacement->sequence, 1U);
  CHECK_EQ(replacement->observationNs, 220U);
  CHECK(!acquisition.ingest(1, samples, 145, 230, 7));
  CHECK(acquisition.available());
  CHECK_EQ(acquisition.generation(), generation + 1);
  // A replacement snapshot coalesced away before socket send must not advance
  // UNAVAILABLE or idle heartbeat generation and reset the host's fade.
  acquisition.invalidate(240);
  CHECK_EQ(acquisition.publishedGeneration(), generation);
  CHECK(!acquisition.available());
  CHECK(acquisition.ingest(1, samples, 250, 260, 7));
  const auto next = acquisition.take();
  CHECK(next->generation > replacement->generation);
  acquisition.published(next->generation);
  CHECK_EQ(acquisition.publishedGeneration(), next->generation);
}

int main() { return RUN_TESTS(); }
